### ISSUE TITLE
Fullscreen support?

### ISSUE THREAD

**Issue by nicl** [jwiegley/emacs-release#1]
Hi,

thanks for the repo - I use OSX and was pointed here by some people on the IRC channel.

Just wondered if this version supports fullscreen mode somehow? Or if you have any tips for this (for native support, as opposed to just making the emacs screen bigger). I have a mac laptop and I'd love to be able to swipe sideways between Emacs and my other applications.

Thanks,

nicl

**Comment by nicl** [comment]
Nm - I figured it out with help from legumbre on IRC...
1. make sure you checkout the mac-port branch (!)
2. configure with the --with-mac option
3. eval the following code:

(set-frame-parameter nil 'fullscreen 'fullboth)

You can eval elisp code by M-: or various other ways...

:)

**Comment by jwiegley** [comment]
I use this code:

(defun emacs-max ()
  (interactive)
  (set-frame-parameter (selected-frame) 'fullscreen 'fullboth)
  (set-frame-parameter (selected-frame) 'vertical-scroll-bars nil)
  (set-frame-parameter (selected-frame) 'horizontal-scroll-bars nil))

(bind-key "C-c m" 'emacs-max)
