### ISSUE TITLE
Does the doc mismatch the 'landmark' game mode?

### ISSUE THREAD

**Issue by snowman** [jwiegley/emacs-release#3]
no problem here

**Comment by balalaXD** [comment]
I got this because `C-h m` in the `*Landmark*` mode.

But look inside of the source code, i found this commentary.
https://github.com/jwiegley/emacs-release/blob/adfd5933358fdf6715423dee8169eb3cd7d982db/lisp/play/landmark.el#L25-L53

**Comment by jwiegley** [comment]
You should report bugs with `M-x report-emacs-bug`. This repository is only a mirror of the release tarballs. Thanks!
